 name: Build Project

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
        
    - name: Create tar archive
      run: |
        mkdir -p /tmp/build-artifacts
        VERSION=$(python setup.py --version)
        PROJECT_NAME=$(python setup.py --name)
        TAR_NAME="${PROJECT_NAME}-${VERSION}.tar"
        tar -cf "/tmp/${TAR_NAME}" dist/
        echo "Archive created at /tmp/${TAR_NAME}"
        
    - name: List created files
      run: |
        ls -la /tmp/*.tar
        ls -la dist/